[template]
src = "gravitee.yml.tmpl"
dest = "/opt/graviteeio-gatewayi/config"
keys = [
"/graviteeio/apim/gateway/http/customize",
"/graviteeio/apim/gateway/http/port",
"/graviteeio/apim/gateway/http/host",
"/graviteeio/apim/gateway/http/idleTimeout",
"/graviteeio/apim/gateway/http/tcpKeepAlive",
"/graviteeio/apim/gateway/http/compressionSupported",
"/graviteeio/apim/gateway/http/instances",
"/graviteeio/apim/gateway/http/secured",
"/graviteeio/apim/gateway/http/alpn",
"/graviteeio/apim/gateway/http/ssl/customize",
"/graviteeio/apim/gateway/http/ssl/clientAuth",
"/graviteeio/apim/gateway/http/ssl/keystore/path",
"/graviteeio/apim/gateway/http/ssl/keystore/secret",
"/graviteeio/apim/gateway/http/ssl/truststore/path",
"/graviteeio/apim/gateway/http/ssl/truststore/secret",
"/graviteeio/apim/gateway/plugins/customize",
"/graviteeio/apim/gateway/plugins/path/generic",
"/graviteeio/apim/gateway/plugins/path/custom",
"/graviteeio/apim/gateway/plugins/failOnDuplicate",
"/graviteeio/apim/gateway/management/datasource/type",
"/graviteeio/apim/gateway/management/datasource/config/type",
"/graviteeio/apim/gateway/management/mongo/config/default/dbname",
"/graviteeio/apim/gateway/management/mongo/config/default/host",
"/graviteeio/apim/gateway/management/mongo/config/default/port",
"/graviteeio/apim/gateway/management/mongo/config/default/username",
"/graviteeio/apim/gateway/management/mongo/config/default/password",
"/graviteeio/apim/gateway/management/mongo/config/connectionsPerHost",
"/graviteeio/apim/gateway/management/mongo/config/connectTimeout",
"/graviteeio/apim/gateway/management/mongo/config/maxWaitTime",
"/graviteeio/apim/gateway/management/mongo/config/socketTimeout",
"/graviteeio/apim/gateway/management/mongo/config/socketKeepAlive",
"/graviteeio/apim/gateway/management/mongo/config/maxConnectionLifeTime",
"/graviteeio/apim/gateway/management/mongo/config/maxConnectionIdleTime",
"/graviteeio/apim/gateway/management/mongo/config/serverSelectionTimeout",
"/graviteeio/apim/gateway/management/mongo/config/description",
"/graviteeio/apim/gateway/management/mongo/config/heartbeatFrequency",
"/graviteeio/apim/gateway/management/mongo/config/minHeartbeatFrequency",
"/graviteeio/apim/gateway/management/mongo/config/heartbeatConnectTimeout",
"/graviteeio/apim/gateway/management/mongo/config/heartbeatSocketTimeout",
"/graviteeio/apim/gateway/management/mongo/config/localThreshold",
"/graviteeio/apim/gateway/management/mongo/config/minConnectionsPerHost",
"/graviteeio/apim/gateway/management/mongo/config/sslEnabled",
"/graviteeio/apim/gateway/management/mongo/config/threadsAllowedToBlockForConnectionMultiplier",
"/graviteeio/apim/gateway/management/mongo/config/cursorFinalizerEnabled",
"/graviteeio/apim/gateway/management/datasource/config/type",
"/graviteeio/apim/gateway/management/mongo/config/uri",
"/graviteeio/apim/gateway/management/datasource/config/type",
"/graviteeio/apim/gateway/management/mongo/config/cluster/servers/1",
"/graviteeio/apim/gateway/management/mongo/config/cluster/servers/2",
"/graviteeio/apim/gateway/management/mongo/config/cluster/servers/3",
"/graviteeio/apim/gateway/management/mongo/config/cluster/servers/4",
"/graviteeio/apim/gateway/management/mongo/config/cluster/servers/5",
"/graviteeio/apim/gateway/management/datasource/type",
"/graviteeio/apim/gateway/ratelimit/mongo/uri/",
"/graviteeio/apim/gateway/management/datasource/type",
"/graviteeio/apim/gateway/ratelimit/dynamo/uri/",
"/graviteeio/apim/gateway/cache/type",
"/graviteeio/apim/gateway/reporters/system/buffersize",
"/graviteeio/apim/gateway/reporters/1",
"/graviteeio/apim/gateway/reporters/2",
"/graviteeio/apim/gateway/reporters/3",
"/graviteeio/apim/gateway/reporters/elasticsearch/enabled",
"/graviteeio/apim/gateway/reporters/elasticsearch/endpoints/type",
"/graviteeio/apim/gateway/reporters/elasticsearch/endpoints/servers/1",
"/graviteeio/apim/gateway/reporters/elasticsearch/endpoints/servers/2",
"/graviteeio/apim/gateway/reporters/elasticsearch/endpoints/servers/3",
"/graviteeio/apim/gateway/reporters/elasticsearch/endpoints/servers/4",
"/graviteeio/apim/gateway/reporters/elasticsearch/endpoints/servers/5",
"/graviteeio/apim/gateway/reporters/elasticsearch/endpoints/servers/6",
"/graviteeio/apim/gateway/reporters/elasticsearch/endpoints/servers/7",
"/graviteeio/apim/gateway/reporters/elasticsearch/endpoints/servers/8",
"/graviteeio/apim/gateway/reporters/elasticsearch/endpoints/servers/9",
"/graviteeio/apim/gateway/reporters/elasticsearch/endpoints/servers/10",
"/graviteeio/apim/gateway/reporters/elasticsearch/endpoints/type",
"/graviteeio/apim/gateway/reporters/elasticsearch/index",
"/graviteeio/apim/gateway/reporters/elasticsearch/cluster",
"/graviteeio/apim/gateway/reporters/elasticsearch/bulk/actions",
"/graviteeio/apim/gateway/reporters/elasticsearch/bulk/flush_interval",
"/graviteeio/apim/gateway/reporters/elasticsearch/bulk/conccurent_requests",
"/graviteeio/apim/gateway/reporters/cloudwatch/enabled",
"/graviteeio/apim/gateway/services/core/http/enabled",
"/graviteeio/apim/gateway/services/core/http/port",
"/graviteeio/apim/gateway/services/core/http/host",
"/graviteeio/apim/gateway/services/core/http/authentication/type",
"/graviteeio/apim/gateway/services/core/http/authentication/users/admin",
"/graviteeio/apim/gateway/services/sync/cron",
"/graviteeio/apim/gateway/services/apikeyscache/delay",
"/graviteeio/apim/gateway/services/apikeyscache/unit",
"/graviteeio/apim/gateway/services/apikeyscache/threads",
"/graviteeio/apim/gateway/services/local/enabled",
"/graviteeio/apim/gateway/services/local/path",
"/graviteeio/apim/gateway/services/monitoring/delay",
"/graviteeio/apim/gateway/services/monitoring/unit",
"/graviteeio/apim/gateway/services/cloudwatch/enabled",
"/graviteeio/apim/gateway/services/cloudwatch/dashboardName",
"/graviteeio/apim/gateway/handlers/request/transaction/header",
"/graviteeio/apim/gateway/tags",
"/graviteeio/apim/gateway/tenant",
"/graviteeio/apim/gateway/policy/customize",
"/graviteeio/apim/gateway/policy/api-key/header",
"/graviteeio/apim/gateway/policy/api-key/param"
]
